CREATE DATABASE DB_GAME_GENERATION_ONLINE;
USE DB_GAME_GENERATION_ONLINE;

CREATE TABLE TB_CLASSES( ID BIGINT (5) AUTO_INCREMENT,
DESCRICAO VARCHAR (255) NOT NULL, 
PRIMARY KEY (ID)
);
CREATE TABLE TB_PERSONAGEM( ID BIGINT (5) AUTO_INCREMENT,
ATLETA VARCHAR (255) NOT NULL,
VESTIMENTA VARCHAR (255) NOT NULL,
HABILIDADE VARCHAR (255) NOT NULL,
DEFESA INT  NOT NULL,
ATAQUE INT NOT NULL,
CLASSES_ID BIGINT,
PRIMARY KEY(ID),
 FOREIGN KEY(CLASSES_ID) REFERENCES TB_CLASSES(ID)
);
INSERT INTO TB_CLASSES(DESCRICAO) VALUES("ESPORTE");
INSERT INTO TB_CLASSES(DESCRICAO) VALUES("ESPORTE");
INSERT INTO TB_CLASSES(DESCRICAO) VALUES("ESPORTE");
INSERT INTO TB_CLASSES(DESCRICAO) VALUES("ESPORTE");
INSERT INTO TB_CLASSES(DESCRICAO) VALUES("ESPORTE");
SELECT * FROM TB_CLASSES;

INSERT INTO TB_PERSONAGEM (ATLETA,VESTIMENTA,HABILIDADE,DEFESA, ATAQUE,CLASSES_ID)
VALUES ("LEO", "UNIFORME", "SOCO",1800,2000, 1);

INSERT INTO TB_PERSONAGEM (ATLETA,VESTIMENTA,HABILIDADE,ATAQUE,DEFESA,CLASSES_ID)
VALUES ("CARLA", "UNIFORME", "CORRIDA",1000,2000,1);

INSERT INTO TB_PERSONAGEM (ATLETA,VESTIMENTA,HABILIDADE,ATAQUE,DEFESA,CLASSES_ID)
VALUES ("JOANA", "UNIFORME", "ESPADA DO SAMURAI",2000,1000,1);

INSERT INTO TB_PERSONAGEM (ATLETA,VESTIMENTA,HABILIDADE,ATAQUE,DEFESA,CLASSES_ID)
VALUES ("HAMILTON", "UNIFORME", "ARCO- FLECHA",1500,1000,1);

INSERT INTO TB_PERSONAGEM (ATLETA,VESTIMENTA,HABILIDADE,ATAQUE,DEFESA,CLASSES_ID)
VALUES ("LEANDRINHO", "UNIFORME", "ARREMEÇO",1100,1800,1);

INSERT INTO TB_PERSONAGEM (ATLETA,VESTIMENTA,HABILIDADE,ATAQUE,DEFESA,CLASSES_ID)
VALUES ("RUBENS", "UNIFORME", "GELO",2000,1999,1);

INSERT INTO TB_PERSONAGEM (ATLETA,VESTIMENTA,HABILIDADE,ATAQUE,DEFESA,CLASSES_ID)
VALUES ("MARTA", "UNIFORME", "DESAPARECER",1000,2000,1);

INSERT INTO TB_PERSONAGEM (ATLETA,VESTIMENTA,HABILIDADE,ATAQUE,DEFESA,CLASSES_ID)
VALUES ("FABIO", "UNIFORME", "CHUTE",1000,1581,1);

DELETE FROM TB_PERSONAGEM WHERE ID = 3;
SELECT * FROM TB_PERSONAGEM;
SELECT * FROM TB_PERSONAGEM WHERE ATAQUE > 2000;
SELECT * FROM TB_PERSONAGEM WHERE DEFESA > 2000 AND DEFESA < 1000;

SELECT *FROM TB_PERSONAGEM WHERE ATLETA LIKE "%C%";

SELECT *FROM TB_PERSONAGEM INNER JOIN TB_CLASSES ON
TB_PERSONAGEM.CLASSES_ID = TB_CLASSES.ID;

SELECT *FROM TB_PERSONAGEM RIGHT JOIN TB_CLASSES ON
TB_PERSONAGEM.CLASSES_ID = TB_CLASSES.ID;




