CREATE DATABASE SERVICO_RH;

USE SERVICO_RH;

CREATE TABLE TB_CONTROLE(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (1000),
GENERO VARCHAR(1000),
PERIODO VARCHAR(1000),
IDADE INT,
SALARIO FLOAT,
PRIMARY KEY (ID)
);

INSERT INTO TB_CONTROLE (NOME,GENERO,PERIODO,IDADE,SALARIO)
VALUES ("MARCELO","MASCULINO","INTEGRAL",45,2000);
INSERT INTO TB_CONTROLE (NOME,GENERO,PERIODO,IDADE,SALARIO)
VALUES ( "MARCOS","MASCULINO","INTEGRA",30,2000);
INSERT INTO TB_CONTROLE (NOME,GENERO,PERIODO,IDADE,SALARIO)
VALUES ( "VITORIA","FEMININO","TARDE",29,1500);
INSERT INTO TB_CONTROLE (NOME,GENERO,PERIODO,IDADE,SALARIO)
VALUES ( "MARIA","FEMININO","INTEGRAL",50,2000);
INSERT INTO TB_CONTROLE (NOME,GENERO,PERIODO,IDADE,SALARIO)
VALUES ( "MIRELA","FEMININO","MANHÃ",25,1500);

SELECT*FROM TB_CONTROLE WHERE SALARIO >2000;
SELECT*FROM TB_CONTROLE WHERE SALARIO <2000;
SET SQL_SAFE_UPDATES=0;
UPDATE TB_CONTROLE SET SALARIO =3000 WHERE  NOME= "MARIA";
