CREATE TABLE `tb_classes` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO `tb_classes` VALUES (1,'ESPORTE');
/*!40000 ALTER TABLE `tb_classes` DISABLE KEYS */;
INSERT INTO `tb_classes` VALUES (1,'ESPORTE');
/*!40000 ALTER TABLE `tb_classes` ENABLE KEYS */;

CREATE TABLE `tb_personagem` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ATLETA` varchar(255) NOT NULL,
  `VESTIMENTA` varchar(255) NOT NULL,
  `HABILIDADE` varchar(255) NOT NULL,
  `DEFESA` int NOT NULL,
  `ATAQUE` int NOT NULL,
  `CLASSES_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CLASSES_ID` (`CLASSES_ID`),
  CONSTRAINT `tb_personagem_ibfk_1` FOREIGN KEY (`CLASSES_ID`) REFERENCES `tb_classes` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*!40000 ALTER TABLE `tb_personagem` DISABLE KEYS */;
INSERT INTO `tb_personagem` VALUES (1,'LEO','UNIFORME','SOCO',1800,2000,1),(4,'CARLA','UNIFORME','CORRIDA',2000,1000,1),(5,'JOANA','UNIFORME','ESPADA DO SAMURAI',1000,2000,1),(6,'HAMILTON','UNIFORME','ARCO- FLECHA',1000,1500,1),(7,'LEANDRINHO','UNIFORME','ARREMEÇO',1800,1100,1),(8,'RUBENS','UNIFORME','GELO',1999,2000,1),(9,'MARTA','UNIFORME','DESAPARECER',2000,1000,1),(10,'FABIO','UNIFORME','CHUTE',1581,1000,1);
/*!40000 ALTER TABLE `tb_personagem` ENABLE KEYS */;